rootProject.name = 'spring-ai'

include("explore-openai")
include("explore-rag")
include("explore-llama")
include("multiple-llms")
include("multimodal-llms")
include("mcp")
include("mcp:mcp-server")
include("mcp:mcp-server:stdio")
include("mcp:mcp-server:webmvc")
include("mcp:mcp-server:webflux")
include("mcp:mcp-server:currency-converter-mcp")
include("mcp:mcp-server:inventory-mcp-server")
include("mcp:mcp-client:fake-mcp-servers")
include("mcp:mcp-client:webmvc")
include("mcp:mcp-client:webflux")
