server:
  port: 8081

spring:
  ai:
    mcp:
      server:
        name: my-weather-server-webflux
        version: 0.0.1
        type: ASYNC
        protocol: STREAMABLE
        streamable-http:
          mcp-endpoint: /mcp

weather:
  api-key: ${WEATHER_API_KEY}
  api-url: http://api.weatherapi.com/v1
